import re
from StringConvertor import StringConvertor
from ErrorMessageCreator import ErrorMessageCreator

class JPPhoneNumberBuilder:
    
    def __init__(self, phone_number : str):

        self._emcreator = ErrorMessageCreator()
        self._strconvertor = StringConvertor()

        out_phone_number = phone_number.strip()
        out_phone_number = out_phone_number.replace('　','')
        out_phone_number = out_phone_number.replace(' ','')
        out_phone_number = out_phone_number.replace('（','')
        out_phone_number = out_phone_number.replace('）','')
        out_phone_number = out_phone_number.replace('(','')
        out_phone_number = out_phone_number.replace(')','')
        out_phone_number = re.sub('[―－−—–‒-]','',out_phone_number)
        out_phone_number = out_phone_number.replace('-','')
        out_phone_number = out_phone_number.replace('+','')
        out_phone_number = out_phone_number.replace('＋','')
        out_phone_number = self._strconvertor.toHankaku(out_phone_number)

        self._phone_number = out_phone_number

    def digits_only(self) -> str:

        if (re.match('^0\d{9}$',self._phone_number)):
            return self._phone_number

        raise ValueError(self._emcreator.message('PhoneNumberBuilder.py','digits_only','invalid argument','the argument is an incompatible phone number.'))

    def hyphenated(self) -> str:
     
        if (re.match('^0\d{9}$',self._phone_number)):

            # 付加的役務電話番号（大量呼受付機能）
            if (self._phone_number[1:4] == '180'):

                body_digits = []

                body_digits.append('991')
                body_digits.append('992')
                body_digits.append('993')
                body_digits.append('994')
                body_digits.append('995')
                body_digits.append('996')
                body_digits.append('997')
                body_digits.append('998')
                body_digits.append('999')

                if (self._phone_number[4:7] in body_digits):
                    return "{}-{}".format(self._phone_number[0:4],self._phone_number[4:])

            # 付加的役務電話番号（着信課金用電話番号）
            if (self._phone_number[1:4] == '120'):

                body_digits = []
                
                body_digits.append('000')
                body_digits.append('001')
                body_digits.append('002')
                body_digits.append('003')
                body_digits.append('004')
                body_digits.append('005')
                body_digits.append('006')
                body_digits.append('007')
                body_digits.append('008')
                body_digits.append('009')

                body_digits.append('010')
                body_digits.append('011')
                body_digits.append('012')
                body_digits.append('013')
                body_digits.append('014')
                body_digits.append('015')
                body_digits.append('016')
                body_digits.append('017')
                body_digits.append('018')
                body_digits.append('019')

                body_digits.append('020')
                body_digits.append('021')
                body_digits.append('022')
                body_digits.append('023')
                body_digits.append('024')
                body_digits.append('025')
                body_digits.append('026')
                body_digits.append('027')
                body_digits.append('028')
                body_digits.append('029')

                body_digits.append('030')
                body_digits.append('031')
                body_digits.append('032')
                body_digits.append('033')
                body_digits.append('034')
                body_digits.append('035')
                body_digits.append('036')
                body_digits.append('037')
                body_digits.append('038')
                body_digits.append('039')

                body_digits.append('040')
                body_digits.append('041')
                body_digits.append('042')
                body_digits.append('043')
                body_digits.append('044')
                body_digits.append('045')
                body_digits.append('046')
                body_digits.append('047')
                body_digits.append('048')
                body_digits.append('049')

                body_digits.append('050')
                body_digits.append('051')
                body_digits.append('052')
                body_digits.append('053')
                body_digits.append('054')
                body_digits.append('055')
                body_digits.append('056')
                body_digits.append('057')
                body_digits.append('058')
                body_digits.append('059')

                body_digits.append('060')
                body_digits.append('061')
                body_digits.append('062')
                body_digits.append('063')
                body_digits.append('064')
                body_digits.append('065')
                body_digits.append('066')
                body_digits.append('067')
                body_digits.append('068')
                body_digits.append('069')

                body_digits.append('070')
                body_digits.append('071')
                body_digits.append('072')
                body_digits.append('073')
                body_digits.append('074')
                body_digits.append('075')
                body_digits.append('076')
                body_digits.append('077')
                body_digits.append('078')
                body_digits.append('079')

                body_digits.append('080')
                body_digits.append('081')
                body_digits.append('082')
                body_digits.append('083')
                body_digits.append('084')
                body_digits.append('085')
                body_digits.append('086')
                body_digits.append('087')
                body_digits.append('088')
                body_digits.append('089')

                body_digits.append('090')
                body_digits.append('091')
                body_digits.append('092')
                body_digits.append('093')
                body_digits.append('094')
                body_digits.append('095')
                body_digits.append('096')
                body_digits.append('097')
                body_digits.append('098')
                body_digits.append('099')

                body_digits.append('100')
                body_digits.append('101')
                body_digits.append('102')
                body_digits.append('103')
                body_digits.append('104')
                body_digits.append('105')
                body_digits.append('106')
                body_digits.append('107')
                body_digits.append('108')
                body_digits.append('109')

                body_digits.append('110')
                body_digits.append('111')
                body_digits.append('112')
                body_digits.append('113')
                body_digits.append('114')
                body_digits.append('115')
                body_digits.append('116')
                body_digits.append('117')
                body_digits.append('118')
                body_digits.append('119')

                body_digits.append('120')
                body_digits.append('121')
                body_digits.append('122')
                body_digits.append('123')
                body_digits.append('124')
                body_digits.append('125')
                body_digits.append('126')
                body_digits.append('127')
                body_digits.append('128')
                body_digits.append('129')

                body_digits.append('130')
                body_digits.append('131')
                body_digits.append('132')
                body_digits.append('133')
                body_digits.append('134')
                body_digits.append('135')
                body_digits.append('136')
                body_digits.append('137')
                body_digits.append('138')
                body_digits.append('139')

                body_digits.append('140')
                body_digits.append('141')
                body_digits.append('142')
                body_digits.append('143')
                body_digits.append('144')
                body_digits.append('145')
                body_digits.append('146')
                body_digits.append('147')
                body_digits.append('148')
                body_digits.append('149')

                body_digits.append('150')
                body_digits.append('151')
                body_digits.append('152')
                body_digits.append('153')
                body_digits.append('154')
                body_digits.append('155')
                body_digits.append('156')
                body_digits.append('157')
                body_digits.append('158')
                body_digits.append('159')

                body_digits.append('160')
                body_digits.append('161')
                body_digits.append('162')
                body_digits.append('163')
                body_digits.append('164')
                body_digits.append('165')
                body_digits.append('166')
                body_digits.append('167')
                body_digits.append('168')
                body_digits.append('169')

                body_digits.append('170')
                body_digits.append('171')
                body_digits.append('172')
                body_digits.append('173')
                body_digits.append('174')
                body_digits.append('175')
                body_digits.append('176')
                body_digits.append('177')
                body_digits.append('178')
                body_digits.append('179')

                body_digits.append('180')
                body_digits.append('181')
                body_digits.append('182')
                body_digits.append('183')
                body_digits.append('184')
                body_digits.append('185')
                body_digits.append('186')
                body_digits.append('187')
                body_digits.append('188')
                body_digits.append('189')

                body_digits.append('190')
                body_digits.append('191')
                body_digits.append('192')
                body_digits.append('193')
                body_digits.append('194')
                body_digits.append('195')
                body_digits.append('196')
                body_digits.append('197')
                body_digits.append('198')
                body_digits.append('199')

                body_digits.append('200')
                body_digits.append('201')
                body_digits.append('202')
                body_digits.append('203')
                body_digits.append('204')
                body_digits.append('205')
                body_digits.append('206')
                body_digits.append('207')
                body_digits.append('208')
                body_digits.append('209')

                body_digits.append('210')
                body_digits.append('211')
                body_digits.append('212')
                body_digits.append('213')
                body_digits.append('214')
                body_digits.append('215')
                body_digits.append('216')
                body_digits.append('217')
                body_digits.append('218')
                body_digits.append('219')

                body_digits.append('220')
                body_digits.append('221')
                body_digits.append('222')
                body_digits.append('223')
                body_digits.append('224')
                body_digits.append('225')
                body_digits.append('226')
                body_digits.append('227')
                body_digits.append('228')
                body_digits.append('229')

                body_digits.append('230')
                body_digits.append('231')
                body_digits.append('232')
                body_digits.append('233')
                body_digits.append('234')
                body_digits.append('235')
                body_digits.append('236')
                body_digits.append('237')
                body_digits.append('238')
                body_digits.append('239')

                body_digits.append('240')
                body_digits.append('241')
                body_digits.append('242')
                body_digits.append('243')
                body_digits.append('244')
                body_digits.append('245')
                body_digits.append('246')
                body_digits.append('247')
                body_digits.append('248')
                body_digits.append('249')

                body_digits.append('250')
                body_digits.append('251')
                body_digits.append('252')
                body_digits.append('253')
                body_digits.append('254')
                body_digits.append('255')
                body_digits.append('256')
                body_digits.append('257')
                body_digits.append('258')
                body_digits.append('259')

                body_digits.append('260')
                body_digits.append('261')
                body_digits.append('262')
                body_digits.append('263')
                body_digits.append('264')
                body_digits.append('265')
                body_digits.append('266')
                body_digits.append('267')
                body_digits.append('268')
                body_digits.append('269')

                body_digits.append('270')
                body_digits.append('271')
                body_digits.append('272')
                body_digits.append('273')
                body_digits.append('274')
                body_digits.append('275')
                body_digits.append('276')
                body_digits.append('277')
                body_digits.append('278')
                body_digits.append('279')

                body_digits.append('280')
                body_digits.append('281')
                body_digits.append('282')
                body_digits.append('283')
                body_digits.append('284')
                body_digits.append('285')
                body_digits.append('286')
                body_digits.append('287')
                body_digits.append('288')
                body_digits.append('289')

                body_digits.append('290')
                body_digits.append('291')
                body_digits.append('292')
                body_digits.append('293')
                body_digits.append('294')
                body_digits.append('295')
                body_digits.append('296')
                body_digits.append('297')
                body_digits.append('298')
                body_digits.append('299')

                body_digits.append('300')
                body_digits.append('301')
                body_digits.append('302')
                body_digits.append('303')
                body_digits.append('304')
                body_digits.append('305')
                body_digits.append('306')
                body_digits.append('307')
                body_digits.append('308')
                body_digits.append('309')

                body_digits.append('310')
                body_digits.append('311')
                body_digits.append('312')
                body_digits.append('313')
                body_digits.append('314')
                body_digits.append('315')
                body_digits.append('316')
                body_digits.append('317')
                body_digits.append('318')
                body_digits.append('319')

                body_digits.append('320')
                body_digits.append('321')
                body_digits.append('322')
                body_digits.append('323')
                body_digits.append('324')
                body_digits.append('325')
                body_digits.append('326')
                body_digits.append('327')
                body_digits.append('328')
                body_digits.append('329')

                body_digits.append('330')
                body_digits.append('331')
                body_digits.append('332')
                body_digits.append('333')
                body_digits.append('334')
                body_digits.append('335')
                body_digits.append('336')
                body_digits.append('337')
                body_digits.append('338')
                body_digits.append('339')

                body_digits.append('340')
                body_digits.append('341')
                body_digits.append('342')
                body_digits.append('343')
                body_digits.append('344')
                body_digits.append('345')
                body_digits.append('346')
                body_digits.append('347')
                body_digits.append('348')
                body_digits.append('349')

                body_digits.append('350')
                body_digits.append('351')
                body_digits.append('352')
                body_digits.append('353')
                body_digits.append('354')
                body_digits.append('355')
                body_digits.append('356')
                body_digits.append('357')
                body_digits.append('358')
                body_digits.append('359')

                body_digits.append('360')
                body_digits.append('361')
                body_digits.append('362')
                body_digits.append('363')
                body_digits.append('364')
                body_digits.append('365')
                body_digits.append('366')
                body_digits.append('367')
                body_digits.append('368')
                body_digits.append('369')

                body_digits.append('370')
                body_digits.append('371')
                body_digits.append('372')
                body_digits.append('373')
                body_digits.append('374')
                body_digits.append('375')
                body_digits.append('376')
                body_digits.append('377')
                body_digits.append('378')
                body_digits.append('379')

                body_digits.append('380')
                body_digits.append('381')
                body_digits.append('382')
                body_digits.append('383')
                body_digits.append('384')
                body_digits.append('385')
                body_digits.append('386')
                body_digits.append('387')
                body_digits.append('388')
                body_digits.append('389')

                body_digits.append('390')
                body_digits.append('391')
                body_digits.append('392')
                body_digits.append('393')
                body_digits.append('394')
                body_digits.append('395')
                body_digits.append('396')
                body_digits.append('397')
                body_digits.append('398')
                body_digits.append('399')

                body_digits.append('400')
                body_digits.append('401')
                body_digits.append('402')
                body_digits.append('403')
                body_digits.append('404')
                body_digits.append('405')
                body_digits.append('406')
                body_digits.append('407')
                body_digits.append('408')
                body_digits.append('409')

                body_digits.append('410')
                body_digits.append('411')
                body_digits.append('412')
                body_digits.append('413')
                body_digits.append('414')
                body_digits.append('415')
                body_digits.append('416')
                body_digits.append('417')
                body_digits.append('418')
                body_digits.append('419')

                body_digits.append('420')
                body_digits.append('421')
                body_digits.append('422')
                body_digits.append('423')
                body_digits.append('424')
                body_digits.append('425')
                body_digits.append('426')
                body_digits.append('427')
                body_digits.append('428')
                body_digits.append('429')

                body_digits.append('430')
                body_digits.append('431')
                body_digits.append('432')
                body_digits.append('433')
                body_digits.append('434')
                body_digits.append('435')
                body_digits.append('436')
                body_digits.append('437')
                body_digits.append('438')
                body_digits.append('439')

                body_digits.append('440')
                body_digits.append('441')
                body_digits.append('442')
                body_digits.append('443')
                body_digits.append('444')
                body_digits.append('445')
                body_digits.append('446')
                body_digits.append('447')
                body_digits.append('448')
                body_digits.append('449')

                body_digits.append('450')
                body_digits.append('451')
                body_digits.append('452')
                body_digits.append('453')
                body_digits.append('454')
                body_digits.append('455')
                body_digits.append('456')
                body_digits.append('457')
                body_digits.append('458')
                body_digits.append('459')

                body_digits.append('460')
                body_digits.append('461')
                body_digits.append('462')
                body_digits.append('463')
                body_digits.append('464')
                body_digits.append('465')
                body_digits.append('466')
                body_digits.append('467')
                body_digits.append('468')
                body_digits.append('469')

                body_digits.append('470')
                body_digits.append('471')
                body_digits.append('472')
                body_digits.append('473')
                body_digits.append('474')
                body_digits.append('475')
                body_digits.append('476')
                body_digits.append('477')
                body_digits.append('478')
                body_digits.append('479')

                body_digits.append('480')
                body_digits.append('481')
                body_digits.append('482')
                body_digits.append('483')
                body_digits.append('484')
                body_digits.append('485')
                body_digits.append('486')
                body_digits.append('487')
                body_digits.append('488')
                body_digits.append('489')

                body_digits.append('490')
                body_digits.append('491')
                body_digits.append('492')
                body_digits.append('493')
                body_digits.append('494')
                body_digits.append('495')
                body_digits.append('496')
                body_digits.append('497')
                body_digits.append('498')
                body_digits.append('499')

                body_digits.append('500')
                body_digits.append('501')
                body_digits.append('502')
                body_digits.append('503')
                body_digits.append('504')
                body_digits.append('505')
                body_digits.append('506')
                body_digits.append('507')
                body_digits.append('508')
                body_digits.append('509')

                body_digits.append('510')
                body_digits.append('511')
                body_digits.append('512')
                body_digits.append('513')
                body_digits.append('514')
                body_digits.append('515')
                body_digits.append('516')
                body_digits.append('517')
                body_digits.append('518')
                body_digits.append('519')

                body_digits.append('520')
                body_digits.append('521')
                body_digits.append('522')
                body_digits.append('523')
                body_digits.append('524')
                body_digits.append('525')
                body_digits.append('526')
                body_digits.append('527')
                body_digits.append('528')
                body_digits.append('529')

                body_digits.append('530')
                body_digits.append('531')
                body_digits.append('532')
                body_digits.append('533')
                body_digits.append('534')
                body_digits.append('535')
                body_digits.append('536')
                body_digits.append('537')
                body_digits.append('538')
                body_digits.append('539')

                body_digits.append('540')
                body_digits.append('541')
                body_digits.append('542')
                body_digits.append('543')
                body_digits.append('544')
                body_digits.append('545')
                body_digits.append('546')
                body_digits.append('547')
                body_digits.append('548')
                body_digits.append('549')

                body_digits.append('550')
                body_digits.append('551')
                body_digits.append('552')
                body_digits.append('553')
                body_digits.append('554')
                body_digits.append('555')
                body_digits.append('556')
                body_digits.append('557')
                body_digits.append('558')
                body_digits.append('559')

                body_digits.append('560')
                body_digits.append('561')
                body_digits.append('562')
                body_digits.append('563')
                body_digits.append('564')
                body_digits.append('565')
                body_digits.append('566')
                body_digits.append('567')
                body_digits.append('568')
                body_digits.append('569')

                body_digits.append('570')
                body_digits.append('571')
                body_digits.append('572')
                body_digits.append('573')
                body_digits.append('574')
                body_digits.append('575')
                body_digits.append('576')
                body_digits.append('577')
                body_digits.append('578')
                body_digits.append('579')

                body_digits.append('580')
                body_digits.append('581')
                body_digits.append('582')
                body_digits.append('583')
                body_digits.append('584')
                body_digits.append('585')
                body_digits.append('586')
                body_digits.append('587')
                body_digits.append('588')
                body_digits.append('589')

                body_digits.append('590')
                body_digits.append('591')
                body_digits.append('592')
                body_digits.append('593')
                body_digits.append('594')
                body_digits.append('595')
                body_digits.append('596')
                body_digits.append('597')
                body_digits.append('598')
                body_digits.append('599')

                body_digits.append('600')
                body_digits.append('601')
                body_digits.append('602')
                body_digits.append('603')
                body_digits.append('604')
                body_digits.append('605')
                body_digits.append('606')
                body_digits.append('607')
                body_digits.append('608')
                body_digits.append('609')

                body_digits.append('610')
                body_digits.append('611')
                body_digits.append('612')
                body_digits.append('613')
                body_digits.append('614')
                body_digits.append('615')
                body_digits.append('616')
                body_digits.append('617')
                body_digits.append('618')
                body_digits.append('619')

                body_digits.append('620')
                body_digits.append('621')
                body_digits.append('622')
                body_digits.append('623')
                body_digits.append('624')
                body_digits.append('625')
                body_digits.append('626')
                body_digits.append('627')
                body_digits.append('628')
                body_digits.append('629')

                body_digits.append('630')
                body_digits.append('631')
                body_digits.append('632')
                body_digits.append('633')
                body_digits.append('634')
                body_digits.append('635')
                body_digits.append('636')
                body_digits.append('637')
                body_digits.append('638')
                body_digits.append('639')

                body_digits.append('640')
                body_digits.append('641')
                body_digits.append('642')
                body_digits.append('643')
                body_digits.append('644')
                body_digits.append('645')
                body_digits.append('646')
                body_digits.append('647')
                body_digits.append('648')
                body_digits.append('649')

                body_digits.append('650')
                body_digits.append('651')
                body_digits.append('652')
                body_digits.append('653')
                body_digits.append('654')
                body_digits.append('655')
                body_digits.append('656')
                body_digits.append('657')
                body_digits.append('658')
                body_digits.append('659')

                body_digits.append('660')
                body_digits.append('661')
                body_digits.append('662')
                body_digits.append('663')
                body_digits.append('664')
                body_digits.append('665')
                body_digits.append('666')
                body_digits.append('667')
                body_digits.append('668')
                body_digits.append('669')

                body_digits.append('670')
                body_digits.append('671')
                body_digits.append('672')
                body_digits.append('673')
                body_digits.append('674')
                body_digits.append('675')
                body_digits.append('676')
                body_digits.append('677')
                body_digits.append('678')
                body_digits.append('679')

                body_digits.append('680')
                body_digits.append('681')
                body_digits.append('682')
                body_digits.append('683')
                body_digits.append('684')
                body_digits.append('685')
                body_digits.append('686')
                body_digits.append('687')
                body_digits.append('688')
                body_digits.append('689')

                body_digits.append('690')
                body_digits.append('691')
                body_digits.append('692')
                body_digits.append('693')
                body_digits.append('694')
                body_digits.append('695')
                body_digits.append('696')
                body_digits.append('697')
                body_digits.append('698')
                body_digits.append('699')

                body_digits.append('700')
                body_digits.append('701')
                body_digits.append('702')
                body_digits.append('703')
                body_digits.append('704')
                body_digits.append('705')
                body_digits.append('706')
                body_digits.append('707')
                body_digits.append('708')
                body_digits.append('709')

                body_digits.append('710')
                body_digits.append('711')
                body_digits.append('712')
                body_digits.append('713')
                body_digits.append('714')
                body_digits.append('715')
                body_digits.append('716')
                body_digits.append('717')
                body_digits.append('718')
                body_digits.append('719')

                body_digits.append('720')
                body_digits.append('721')
                body_digits.append('722')
                body_digits.append('723')
                body_digits.append('724')
                body_digits.append('725')
                body_digits.append('726')
                body_digits.append('727')
                body_digits.append('728')
                body_digits.append('729')

                body_digits.append('730')
                body_digits.append('731')
                body_digits.append('732')
                body_digits.append('733')
                body_digits.append('734')
                body_digits.append('735')
                body_digits.append('736')
                body_digits.append('737')
                body_digits.append('738')
                body_digits.append('739')

                body_digits.append('740')
                body_digits.append('741')
                body_digits.append('742')
                body_digits.append('743')
                body_digits.append('744')
                body_digits.append('745')
                body_digits.append('746')
                body_digits.append('747')
                body_digits.append('748')
                body_digits.append('749')

                body_digits.append('750')
                body_digits.append('751')
                body_digits.append('752')
                body_digits.append('753')
                body_digits.append('754')
                body_digits.append('755')
                body_digits.append('756')
                body_digits.append('757')
                body_digits.append('758')
                body_digits.append('759')

                body_digits.append('760')
                body_digits.append('761')
                body_digits.append('762')
                body_digits.append('763')
                body_digits.append('764')
                body_digits.append('765')
                body_digits.append('766')
                body_digits.append('767')
                body_digits.append('768')
                body_digits.append('769')

                body_digits.append('770')
                body_digits.append('771')
                body_digits.append('772')
                body_digits.append('773')
                body_digits.append('774')
                body_digits.append('775')
                body_digits.append('776')
                body_digits.append('777')
                body_digits.append('778')
                body_digits.append('779')

                body_digits.append('780')
                body_digits.append('781')
                body_digits.append('782')
                body_digits.append('783')
                body_digits.append('784')
                body_digits.append('785')
                body_digits.append('786')
                body_digits.append('787')
                body_digits.append('788')
                body_digits.append('789')

                body_digits.append('790')
                body_digits.append('791')
                body_digits.append('792')
                body_digits.append('793')
                body_digits.append('794')
                body_digits.append('795')
                body_digits.append('796')
                body_digits.append('797')
                body_digits.append('798')
                body_digits.append('799')

                body_digits.append('800')
                body_digits.append('801')
                body_digits.append('802')
                body_digits.append('803')
                body_digits.append('804')
                body_digits.append('805')
                body_digits.append('806')
                body_digits.append('807')
                body_digits.append('808')
                body_digits.append('809')

                body_digits.append('810')
                body_digits.append('811')
                body_digits.append('812')
                body_digits.append('813')
                body_digits.append('814')
                body_digits.append('815')
                body_digits.append('816')
                body_digits.append('817')
                body_digits.append('818')
                body_digits.append('819')

                body_digits.append('820')
                body_digits.append('821')
                body_digits.append('822')
                body_digits.append('823')
                body_digits.append('824')
                body_digits.append('825')
                body_digits.append('826')
                body_digits.append('827')
                body_digits.append('828')
                body_digits.append('829')

                body_digits.append('830')
                body_digits.append('831')
                body_digits.append('832')
                body_digits.append('833')
                body_digits.append('834')
                body_digits.append('835')
                body_digits.append('836')
                body_digits.append('837')
                body_digits.append('838')
                body_digits.append('839')

                body_digits.append('840')
                body_digits.append('841')
                body_digits.append('842')
                body_digits.append('843')
                body_digits.append('844')
                body_digits.append('845')
                body_digits.append('846')
                body_digits.append('847')
                body_digits.append('848')
                body_digits.append('849')

                body_digits.append('850')
                body_digits.append('851')
                body_digits.append('852')
                body_digits.append('853')
                body_digits.append('854')
                body_digits.append('855')
                body_digits.append('856')
                body_digits.append('857')
                body_digits.append('858')
                body_digits.append('859')

                body_digits.append('860')
                body_digits.append('861')
                body_digits.append('862')
                body_digits.append('863')
                body_digits.append('864')
                body_digits.append('865')
                body_digits.append('866')
                body_digits.append('867')
                body_digits.append('868')
                body_digits.append('869')

                body_digits.append('870')
                body_digits.append('871')
                body_digits.append('872')
                body_digits.append('873')
                body_digits.append('874')
                body_digits.append('875')
                body_digits.append('876')
                body_digits.append('877')
                body_digits.append('878')
                body_digits.append('879')

                body_digits.append('880')
                body_digits.append('881')
                body_digits.append('882')
                body_digits.append('883')
                body_digits.append('884')
                body_digits.append('885')
                body_digits.append('886')
                body_digits.append('887')
                body_digits.append('888')
                body_digits.append('889')

                body_digits.append('890')
                body_digits.append('891')
                body_digits.append('892')
                body_digits.append('893')
                body_digits.append('894')
                body_digits.append('895')
                body_digits.append('896')
                body_digits.append('897')
                body_digits.append('898')
                body_digits.append('899')

                body_digits.append('900')
                body_digits.append('901')
                #body_digits.append('902')
                #body_digits.append('903')
                #body_digits.append('904')
                body_digits.append('905')
                #body_digits.append('906')
                body_digits.append('907')
                #body_digits.append('908')
                #body_digits.append('909')

                body_digits.append('910')
                body_digits.append('911')
                body_digits.append('912')
                body_digits.append('913')
                body_digits.append('914')
                body_digits.append('915')
                body_digits.append('916')
                body_digits.append('917')
                body_digits.append('918')
                body_digits.append('919')

                body_digits.append('920')
                body_digits.append('921')
                body_digits.append('922')
                body_digits.append('923')
                body_digits.append('924')
                body_digits.append('925')
                body_digits.append('926')
                body_digits.append('927')
                body_digits.append('928')
                body_digits.append('929')

                body_digits.append('930')
                body_digits.append('931')
                body_digits.append('932')
                body_digits.append('933')
                body_digits.append('934')
                body_digits.append('935')
                body_digits.append('936')
                body_digits.append('937')
                body_digits.append('938')
                body_digits.append('939')

                body_digits.append('940')
                body_digits.append('941')
                #body_digits.append('942')
                #body_digits.append('943')
                body_digits.append('944')
                body_digits.append('945')
                body_digits.append('946')
                body_digits.append('947')
                body_digits.append('948')
                body_digits.append('949')

                body_digits.append('950')
                body_digits.append('951')
                body_digits.append('952')
                body_digits.append('953')
                body_digits.append('954')
                body_digits.append('955')
                body_digits.append('956')
                body_digits.append('957')
                body_digits.append('958')
                body_digits.append('959')

                body_digits.append('960')
                body_digits.append('961')
                body_digits.append('962')
                body_digits.append('963')
                body_digits.append('964')
                body_digits.append('965')
                body_digits.append('966')
                body_digits.append('967')
                body_digits.append('968')
                body_digits.append('969')

                body_digits.append('970')
                body_digits.append('971')
                body_digits.append('972')
                body_digits.append('973')
                body_digits.append('974')
                body_digits.append('975')
                body_digits.append('976')
                body_digits.append('977')
                body_digits.append('978')
                body_digits.append('979')

                body_digits.append('980')
                body_digits.append('981')
                body_digits.append('982')
                body_digits.append('983')
                body_digits.append('984')
                body_digits.append('985')
                body_digits.append('986')
                body_digits.append('987')
                body_digits.append('988')
                body_digits.append('989')

                body_digits.append('990')
                body_digits.append('991')
                body_digits.append('992')
                body_digits.append('993')
                body_digits.append('994')
                body_digits.append('995')
                body_digits.append('996')
                body_digits.append('997')
                body_digits.append('998')
                body_digits.append('999')

                if (self._phone_number[4:7] in body_digits):
                    return "{}-{}-{}".format(self._phone_number[0:4],self._phone_number[4:7],self._phone_number[7:])

            # 付加的役務電話番号（統一番号機能）
            if (self._phone_number[1:4] == '570'):

                body_digits = []

                body_digits.append('000')
                body_digits.append('001')
                body_digits.append('002')
                body_digits.append('003')
                body_digits.append('004')
                body_digits.append('005')
                body_digits.append('006')
                body_digits.append('007')
                body_digits.append('008')
                body_digits.append('009')

                body_digits.append('010')
                body_digits.append('011')
                body_digits.append('012')
                body_digits.append('013')
                body_digits.append('014')
                body_digits.append('015')
                body_digits.append('016')
                body_digits.append('017')
                body_digits.append('018')
                body_digits.append('019')

                body_digits.append('020')
                body_digits.append('021')
                body_digits.append('022')
                body_digits.append('023')
                body_digits.append('024')
                body_digits.append('025')
                body_digits.append('026')
                body_digits.append('027')
                body_digits.append('028')
                body_digits.append('029')

                body_digits.append('030')
                body_digits.append('031')
                body_digits.append('032')
                body_digits.append('033')
                body_digits.append('034')
                body_digits.append('035')
                body_digits.append('036')
                body_digits.append('037')
                body_digits.append('038')
                body_digits.append('039')

                body_digits.append('040')
                body_digits.append('041')
                body_digits.append('042')
                body_digits.append('043')
                body_digits.append('044')
                body_digits.append('045')
                body_digits.append('046')
                body_digits.append('047')
                body_digits.append('048')
                body_digits.append('049')

                body_digits.append('050')
                body_digits.append('051')
                body_digits.append('052')
                body_digits.append('053')
                body_digits.append('054')
                body_digits.append('055')
                body_digits.append('056')
                body_digits.append('057')
                body_digits.append('058')
                body_digits.append('059')

                body_digits.append('060')
                body_digits.append('061')
                body_digits.append('062')
                body_digits.append('063')
                body_digits.append('064')
                body_digits.append('065')
                body_digits.append('066')
                body_digits.append('067')
                body_digits.append('068')
                body_digits.append('069')

                body_digits.append('070')
                body_digits.append('071')
                body_digits.append('072')
                body_digits.append('073')
                body_digits.append('074')
                body_digits.append('075')
                body_digits.append('076')
                body_digits.append('077')
                body_digits.append('078')
                body_digits.append('079')

                body_digits.append('080')
                body_digits.append('081')
                body_digits.append('082')
                body_digits.append('083')
                body_digits.append('084')
                body_digits.append('085')
                body_digits.append('086')
                body_digits.append('087')
                body_digits.append('088')
                body_digits.append('089')

                body_digits.append('090')
                body_digits.append('091')
                body_digits.append('092')
                body_digits.append('093')
                body_digits.append('094')
                body_digits.append('095')
                body_digits.append('096')
                body_digits.append('097')
                body_digits.append('098')
                body_digits.append('099')

                body_digits.append('200')
                body_digits.append('300')
                
                body_digits.append('550')
                body_digits.append('570')
                body_digits.append('571')
                body_digits.append('572')

                body_digits.append('666')
                body_digits.append('783')

                body_digits.append('881')
                body_digits.append('882')
                body_digits.append('888')

                body_digits.append('919')
                body_digits.append('943')
                body_digits.append('999')

                if (self._phone_number[4:7] in body_digits):
                    return "{}-{}-{}".format(self._phone_number[0:4],self._phone_number[4:7],self._phone_number[7:])
            
            # 固定電話 - 市外局番 : 3桁
            #head_digits = []
            #head_digits.append('123')

            phone_book_3digits = {'123':[]}

            phone_book_3digits['123'].append('20')
            phone_book_3digits['123'].append('21')
            phone_book_3digits['123'].append('22')
            phone_book_3digits['123'].append('23')
            phone_book_3digits['123'].append('24')
            phone_book_3digits['123'].append('25')
            phone_book_3digits['123'].append('26')
            phone_book_3digits['123'].append('27')
            phone_book_3digits['123'].append('28')
            phone_book_3digits['123'].append('29')

            #phone_book_3digits['123'].append('30')
            phone_book_3digits['123'].append('31')
            phone_book_3digits['123'].append('32')
            phone_book_3digits['123'].append('33')
            phone_book_3digits['123'].append('34')
            phone_book_3digits['123'].append('35')
            phone_book_3digits['123'].append('36')
            phone_book_3digits['123'].append('37')
            phone_book_3digits['123'].append('38')
            phone_book_3digits['123'].append('39')

            phone_book_3digits['123'].append('40')
            #phone_book_3digits['123'].append('41')
            phone_book_3digits['123'].append('42')
            phone_book_3digits['123'].append('43')
            #phone_book_3digits['123'].append('44')
            phone_book_3digits['123'].append('45')
            phone_book_3digits['123'].append('46')
            phone_book_3digits['123'].append('47')
            phone_book_3digits['123'].append('48')
            phone_book_3digits['123'].append('49')

            phone_book_3digits['123'].append('50')
            #phone_book_3digits['123'].append('51')
            phone_book_3digits['123'].append('52')
            phone_book_3digits['123'].append('53')
            phone_book_3digits['123'].append('54')
            phone_book_3digits['123'].append('55')
            phone_book_3digits['123'].append('56')
            phone_book_3digits['123'].append('57')
            phone_book_3digits['123'].append('58')
            phone_book_3digits['123'].append('59')

            #phone_book_3digits['123'].append('60')
            #phone_book_3digits['123'].append('61')
            # phone_book_3digits['123'].append('62')
            # phone_book_3digits['123'].append('63')
            # phone_book_3digits['123'].append('64')
            # phone_book_3digits['123'].append('65')
            phone_book_3digits['123'].append('66')
            #phone_book_3digits['123'].append('67')
            phone_book_3digits['123'].append('68')
            #phone_book_3digits['123'].append('69')

            # phone_book_3digits['123'].append('70')
            # phone_book_3digits['123'].append('71')
            phone_book_3digits['123'].append('72')
            phone_book_3digits['123'].append('73')
            phone_book_3digits['123'].append('74')
            phone_book_3digits['123'].append('75')
            phone_book_3digits['123'].append('76')
            phone_book_3digits['123'].append('77')
            phone_book_3digits['123'].append('78')
            # phone_book_3digits['123'].append('79')

            # phone_book_3digits['123'].append('80')
            # phone_book_3digits['123'].append('81')
            phone_book_3digits['123'].append('82')
            phone_book_3digits['123'].append('83')
            phone_book_3digits['123'].append('84')
            phone_book_3digits['123'].append('85')
            phone_book_3digits['123'].append('86')
            phone_book_3digits['123'].append('87')
            phone_book_3digits['123'].append('88')
            phone_book_3digits['123'].append('89')

            # phone_book_3digits['123'].append('90')
            # phone_book_3digits['123'].append('91')
            phone_book_3digits['123'].append('92')
            phone_book_3digits['123'].append('93')
            # phone_book_3digits['123'].append('94')
            # phone_book_3digits['123'].append('95')
            # phone_book_3digits['123'].append('96')
            # phone_book_3digits['123'].append('97')
            phone_book_3digits['123'].append('98')
            # phone_book_3digits['123'].append('99')

            head_3digits = self._phone_number[1:4]

            if (head_3digits in phone_book_3digits):

                if (self._phone_number[4:6] in phone_book_3digits[head_3digits]):
                    return f"{self._phone_number[0:4]}-{self._phone_number[4:6]}-{self._phone_number[6:]}"

            phone_book_3digits.clear()

            # 固定電話 - 市外局番 : 2桁
            #head_digits = []
            #head_digits.append('11')

            phone_book_2digits = {'11' : []}

            phone_book_2digits['11'].append('200')
            phone_book_2digits['11'].append('201')
            phone_book_2digits['11'].append('202')
            phone_book_2digits['11'].append('203')
            phone_book_2digits['11'].append('204')
            phone_book_2digits['11'].append('205')
            phone_book_2digits['11'].append('206')
            phone_book_2digits['11'].append('207')
            phone_book_2digits['11'].append('208')
            phone_book_2digits['11'].append('209')

            phone_book_2digits['11'].append('210')
            phone_book_2digits['11'].append('211')
            phone_book_2digits['11'].append('212')
            phone_book_2digits['11'].append('213')
            phone_book_2digits['11'].append('214')
            phone_book_2digits['11'].append('215')
            #phone_book_2digits['11'].append('216')
            #phone_book_2digits['11'].append('217')
            phone_book_2digits['11'].append('218')
            phone_book_2digits['11'].append('219')

            #phone_book_2digits['11'].append('220')
            phone_book_2digits['11'].append('221')
            phone_book_2digits['11'].append('222')
            phone_book_2digits['11'].append('223')
            #phone_book_2digits['11'].append('224')
            #phone_book_2digits['11'].append('225')
            #phone_book_2digits['11'].append('226')
            #phone_book_2digits['11'].append('227')
            #phone_book_2digits['11'].append('228')
            #phone_book_2digits['11'].append('229')

            #phone_book_2digits['11'].append('230')
            phone_book_2digits['11'].append('231')
            phone_book_2digits['11'].append('232')
            phone_book_2digits['11'].append('233')
            phone_book_2digits['11'].append('234')
            #phone_book_2digits['11'].append('235')
            #phone_book_2digits['11'].append('236')
            #phone_book_2digits['11'].append('237')
            #phone_book_2digits['11'].append('238')
            #phone_book_2digits['11'].append('239')

            #phone_book_2digits['11'].append('240')
            phone_book_2digits['11'].append('241')
            phone_book_2digits['11'].append('242')
            #phone_book_2digits['11'].append('243')
            #phone_book_2digits['11'].append('244')
            #phone_book_2digits['11'].append('245')
            #phone_book_2digits['11'].append('246')
            #phone_book_2digits['11'].append('247')
            #phone_book_2digits['11'].append('248')
            #phone_book_2digits['11'].append('249')

            #phone_book_2digits['11'].append('250')
            phone_book_2digits['11'].append('251')
            phone_book_2digits['11'].append('252')
            #phone_book_2digits['11'].append('253')
            #phone_book_2digits['11'].append('254')
            #phone_book_2digits['11'].append('255')
            #phone_book_2digits['11'].append('256')
            #phone_book_2digits['11'].append('257')
            #phone_book_2digits['11'].append('258')
            #phone_book_2digits['11'].append('259')

            #phone_book_2digits['11'].append('260')
            phone_book_2digits['11'].append('261')
            #phone_book_2digits['11'].append('262')
            #phone_book_2digits['11'].append('263')
            #phone_book_2digits['11'].append('264')
            #phone_book_2digits['11'].append('265')
            #phone_book_2digits['11'].append('266')
            #phone_book_2digits['11'].append('267')
            #phone_book_2digits['11'].append('269')

            #phone_book_2digits['11'].append('270')
            phone_book_2digits['11'].append('271')
            phone_book_2digits['11'].append('272')
            #phone_book_2digits['11'].append('273')
            #phone_book_2digits['11'].append('274')
            #phone_book_2digits['11'].append('275')
            #phone_book_2digits['11'].append('276')
            #phone_book_2digits['11'].append('277')
            #phone_book_2digits['11'].append('278')
            #phone_book_2digits['11'].append('279')

            phone_book_2digits['11'].append('280')
            phone_book_2digits['11'].append('281')
            #phone_book_2digits['11'].append('282')
            #phone_book_2digits['11'].append('283')
            #phone_book_2digits['11'].append('284')
            #phone_book_2digits['11'].append('285')
            #phone_book_2digits['11'].append('286')
            #phone_book_2digits['11'].append('287')
            #phone_book_2digits['11'].append('288')
            #phone_book_2digits['11'].append('289')

            phone_book_2digits['11'].append('290')
            #phone_book_2digits['11'].append('291')
            #phone_book_2digits['11'].append('292')
            #phone_book_2digits['11'].append('293')
            #phone_book_2digits['11'].append('294')
            #phone_book_2digits['11'].append('295')
            #phone_book_2digits['11'].append('296')
            #phone_book_2digits['11'].append('297')
            #phone_book_2digits['11'].append('298')
            phone_book_2digits['11'].append('299')

            phone_book_2digits['11'].append('300')
            phone_book_2digits['11'].append('301')
            phone_book_2digits['11'].append('302')
            phone_book_2digits['11'].append('303')
            #phone_book_2digits['11'].append('304')
            #phone_book_2digits['11'].append('305')
            #phone_book_2digits['11'].append('306')
            #phone_book_2digits['11'].append('307')
            #phone_book_2digits['11'].append('308')
            #phone_book_2digits['11'].append('309')

            #phone_book_2digits['11'].append('310')
            phone_book_2digits['11'].append('311')
            phone_book_2digits['11'].append('312')
            phone_book_2digits['11'].append('313')
            phone_book_2digits['11'].append('314')
            #phone_book_2digits['11'].append('315')
            #phone_book_2digits['11'].append('316')
            #phone_book_2digits['11'].append('317')
            #phone_book_2digits['11'].append('318')
            #phone_book_2digits['11'].append('319')

            #phone_book_2digits['11'].append('320')
            #phone_book_2digits['11'].append('321')
            #phone_book_2digits['11'].append('322')
            #phone_book_2digits['11'].append('323')
            #phone_book_2digits['11'].append('324')
            phone_book_2digits['11'].append('325')
            #phone_book_2digits['11'].append('326')
            #phone_book_2digits['11'].append('327')
            #phone_book_2digits['11'].append('328')
            #phone_book_2digits['11'].append('329')

            phone_book_2digits['11'].append('330')
            #phone_book_2digits['11'].append('331')
            #phone_book_2digits['11'].append('332')
            #phone_book_2digits['11'].append('333')
            #phone_book_2digits['11'].append('334')
            #phone_book_2digits['11'].append('335')
            #phone_book_2digits['11'].append('336')
            #phone_book_2digits['11'].append('337')
            #phone_book_2digits['11'].append('338')
            #phone_book_2digits['11'].append('339')

            #phone_book_2digits['11'].append('340')
            #phone_book_2digits['11'].append('341')
            #phone_book_2digits['11'].append('342')
            #phone_book_2digits['11'].append('343')
            #phone_book_2digits['11'].append('344')
            #phone_book_2digits['11'].append('345')
            #phone_book_2digits['11'].append('346')
            #phone_book_2digits['11'].append('347')
            #phone_book_2digits['11'].append('348')
            #phone_book_2digits['11'].append('349')

            phone_book_2digits['11'].append('350')
            phone_book_2digits['11'].append('351')
            #phone_book_2digits['11'].append('352')
            #phone_book_2digits['11'].append('353')
            #phone_book_2digits['11'].append('354')
            #phone_book_2digits['11'].append('355')
            #phone_book_2digits['11'].append('356')
            #phone_book_2digits['11'].append('357')
            #phone_book_2digits['11'].append('358')
            #phone_book_2digits['11'].append('359')

            #phone_book_2digits['11'].append('360')
            #phone_book_2digits['11'].append('361')
            #phone_book_2digits['11'].append('362')
            #phone_book_2digits['11'].append('363')
            #phone_book_2digits['11'].append('364')
            #phone_book_2digits['11'].append('365')
            #phone_book_2digits['11'].append('366')
            #phone_book_2digits['11'].append('367')
            #phone_book_2digits['11'].append('368')
            #phone_book_2digits['11'].append('369')

            phone_book_2digits['11'].append('370')
            #phone_book_2digits['11'].append('371')
            phone_book_2digits['11'].append('372')
            phone_book_2digits['11'].append('373')
            phone_book_2digits['11'].append('374')
            phone_book_2digits['11'].append('375')
            phone_book_2digits['11'].append('376')
            phone_book_2digits['11'].append('377')
            phone_book_2digits['11'].append('378')
            #phone_book_2digits['11'].append('379')

            phone_book_2digits['11'].append('380')
            phone_book_2digits['11'].append('381')
            phone_book_2digits['11'].append('382')
            phone_book_2digits['11'].append('383')
            phone_book_2digits['11'].append('384')
            phone_book_2digits['11'].append('385')
            phone_book_2digits['11'].append('386')
            phone_book_2digits['11'].append('387')
            phone_book_2digits['11'].append('388')
            phone_book_2digits['11'].append('389')

            #phone_book_2digits['11'].append('390')
            phone_book_2digits['11'].append('391')
            #phone_book_2digits['11'].append('392')
            #phone_book_2digits['11'].append('393')
            #phone_book_2digits['11'].append('394')
            #phone_book_2digits['11'].append('395')
            #phone_book_2digits['11'].append('396')
            #phone_book_2digits['11'].append('397')
            phone_book_2digits['11'].append('398')
            #phone_book_2digits['11'].append('399')

            #phone_book_2digits['11'].append('400')
            #phone_book_2digits['11'].append('401')
            #phone_book_2digits['11'].append('402')
            #phone_book_2digits['11'].append('403')
            #phone_book_2digits['11'].append('404')
            #phone_book_2digits['11'].append('405')
            #phone_book_2digits['11'].append('406')
            #phone_book_2digits['11'].append('407')
            #phone_book_2digits['11'].append('408')
            #phone_book_2digits['11'].append('409')

            #phone_book_2digits['11'].append('410')
            #phone_book_2digits['11'].append('411')
            #phone_book_2digits['11'].append('412')
            #phone_book_2digits['11'].append('413')
            #phone_book_2digits['11'].append('414')
            #phone_book_2digits['11'].append('415')
            #phone_book_2digits['11'].append('416')
            #phone_book_2digits['11'].append('417')
            #phone_book_2digits['11'].append('418')
            #phone_book_2digits['11'].append('419')

            #phone_book_2digits['11'].append('420')
            #phone_book_2digits['11'].append('421')
            #phone_book_2digits['11'].append('422')
            #phone_book_2digits['11'].append('423')
            #phone_book_2digits['11'].append('424')
            #phone_book_2digits['11'].append('425')
            #phone_book_2digits['11'].append('426')
            #phone_book_2digits['11'].append('427')
            #phone_book_2digits['11'].append('428')
            #phone_book_2digits['11'].append('429')

            # phone_book_2digits['11'].append('430')
            # phone_book_2digits['11'].append('431')
            # phone_book_2digits['11'].append('432')
            # phone_book_2digits['11'].append('433')
            # phone_book_2digits['11'].append('434')
            # phone_book_2digits['11'].append('435')
            # phone_book_2digits['11'].append('436')
            # phone_book_2digits['11'].append('437')
            # phone_book_2digits['11'].append('438')
            # phone_book_2digits['11'].append('439')

            # phone_book_2digits['11'].append('440')
            # phone_book_2digits['11'].append('441')
            # phone_book_2digits['11'].append('442')
            # phone_book_2digits['11'].append('443')
            # phone_book_2digits['11'].append('444')
            # phone_book_2digits['11'].append('445')
            # phone_book_2digits['11'].append('446')
            # phone_book_2digits['11'].append('447')
            # phone_book_2digits['11'].append('448')
            # phone_book_2digits['11'].append('449')

            # phone_book_2digits['11'].append('450')
            # phone_book_2digits['11'].append('451')
            # phone_book_2digits['11'].append('452')
            # phone_book_2digits['11'].append('453')
            # phone_book_2digits['11'].append('454')
            # phone_book_2digits['11'].append('455')
            # phone_book_2digits['11'].append('456')
            # phone_book_2digits['11'].append('457')
            # phone_book_2digits['11'].append('458')
            # phone_book_2digits['11'].append('459')

            # phone_book_2digits['11'].append('460')
            # phone_book_2digits['11'].append('461')
            # phone_book_2digits['11'].append('462')
            # phone_book_2digits['11'].append('463')
            # phone_book_2digits['11'].append('464')
            # phone_book_2digits['11'].append('465')
            # phone_book_2digits['11'].append('466')
            # phone_book_2digits['11'].append('467')
            # phone_book_2digits['11'].append('468')
            # phone_book_2digits['11'].append('469')

            # phone_book_2digits['11'].append('470')
            # phone_book_2digits['11'].append('471')
            # phone_book_2digits['11'].append('472')
            # phone_book_2digits['11'].append('473')
            # phone_book_2digits['11'].append('474')
            # phone_book_2digits['11'].append('475')
            # phone_book_2digits['11'].append('476')
            # phone_book_2digits['11'].append('477')
            # phone_book_2digits['11'].append('478')
            # phone_book_2digits['11'].append('479')

            # phone_book_2digits['11'].append('480')
            # phone_book_2digits['11'].append('481')
            # phone_book_2digits['11'].append('482')
            # phone_book_2digits['11'].append('483')
            # phone_book_2digits['11'].append('484')
            # phone_book_2digits['11'].append('485')
            # phone_book_2digits['11'].append('486')
            # phone_book_2digits['11'].append('487')
            # phone_book_2digits['11'].append('488')
            # phone_book_2digits['11'].append('489')

            # phone_book_2digits['11'].append('490')
            # phone_book_2digits['11'].append('491')
            # phone_book_2digits['11'].append('492')
            # phone_book_2digits['11'].append('493')
            # phone_book_2digits['11'].append('494')
            # phone_book_2digits['11'].append('495')
            # phone_book_2digits['11'].append('496')
            # phone_book_2digits['11'].append('497')
            # phone_book_2digits['11'].append('498')
            # phone_book_2digits['11'].append('499')

            phone_book_2digits['11'].append('500')
            phone_book_2digits['11'].append('501')
            #phone_book_2digits['11'].append('502')
            #phone_book_2digits['11'].append('503')
            #phone_book_2digits['11'].append('504')
            #phone_book_2digits['11'].append('505')
            #phone_book_2digits['11'].append('506')
            #phone_book_2digits['11'].append('507')
            #phone_book_2digits['11'].append('508')
            #phone_book_2digits['11'].append('509')

            #phone_book_2digits['11'].append('510')
            phone_book_2digits['11'].append('511')
            phone_book_2digits['11'].append('512')
            phone_book_2digits['11'].append('513')
            #phone_book_2digits['11'].append('514')
            #phone_book_2digits['11'].append('515')
            #phone_book_2digits['11'].append('516')
            #phone_book_2digits['11'].append('517')
            phone_book_2digits['11'].append('518')
            #phone_book_2digits['11'].append('519')

            phone_book_2digits['11'].append('520')
            phone_book_2digits['11'].append('521')
            phone_book_2digits['11'].append('522')
            #phone_book_2digits['11'].append('523')
            #phone_book_2digits['11'].append('524')
            #phone_book_2digits['11'].append('525')
            #phone_book_2digits['11'].append('526')
            #phone_book_2digits['11'].append('527')
            #phone_book_2digits['11'].append('528')
            #phone_book_2digits['11'].append('529')

            phone_book_2digits['11'].append('530')
            phone_book_2digits['11'].append('531')
            phone_book_2digits['11'].append('532')
            phone_book_2digits['11'].append('533')
            # phone_book_2digits['11'].append('534')
            # phone_book_2digits['11'].append('535')
            # phone_book_2digits['11'].append('536')
            # phone_book_2digits['11'].append('537')
            # phone_book_2digits['11'].append('538')
            # phone_book_2digits['11'].append('539')

            # phone_book_2digits['11'].append('540')
            # phone_book_2digits['11'].append('541')
            # phone_book_2digits['11'].append('542')
            # phone_book_2digits['11'].append('543')
            # phone_book_2digits['11'].append('544')
            # phone_book_2digits['11'].append('545')
            # phone_book_2digits['11'].append('546')
            # phone_book_2digits['11'].append('547')
            # phone_book_2digits['11'].append('548')
            # phone_book_2digits['11'].append('549')

            #phone_book_2digits['11'].append('550')
            phone_book_2digits['11'].append('551')
            phone_book_2digits['11'].append('552')
            #phone_book_2digits['11'].append('553')
            #phone_book_2digits['11'].append('554')
            phone_book_2digits['11'].append('555')
            phone_book_2digits['11'].append('556')
            phone_book_2digits['11'].append('557')
            phone_book_2digits['11'].append('558')
            #phone_book_2digits['11'].append('559')

            #phone_book_2digits['11'].append('560')
            phone_book_2digits['11'].append('561')
            phone_book_2digits['11'].append('562')
            phone_book_2digits['11'].append('563')
            # phone_book_2digits['11'].append('564')
            # phone_book_2digits['11'].append('565')
            # phone_book_2digits['11'].append('566')
            # phone_book_2digits['11'].append('567')
            # phone_book_2digits['11'].append('568')
            # phone_book_2digits['11'].append('569')

            #phone_book_2digits['11'].append('570')
            phone_book_2digits['11'].append('571')
            phone_book_2digits['11'].append('572')
            phone_book_2digits['11'].append('573')
            # phone_book_2digits['11'].append('574')
            # phone_book_2digits['11'].append('575')
            # phone_book_2digits['11'].append('576')
            phone_book_2digits['11'].append('577')
            phone_book_2digits['11'].append('578')
            #phone_book_2digits['11'].append('579')

            #phone_book_2digits['11'].append('580')
            phone_book_2digits['11'].append('581')
            phone_book_2digits['11'].append('582')
            phone_book_2digits['11'].append('583')
            phone_book_2digits['11'].append('584')
            phone_book_2digits['11'].append('585')
            # phone_book_2digits['11'].append('586')
            # phone_book_2digits['11'].append('587')
            phone_book_2digits['11'].append('588')
            #phone_book_2digits['11'].append('589')

            phone_book_2digits['11'].append('590')
            phone_book_2digits['11'].append('591')
            phone_book_2digits['11'].append('592')
            phone_book_2digits['11'].append('593')
            phone_book_2digits['11'].append('594')
            phone_book_2digits['11'].append('595')
            phone_book_2digits['11'].append('596')
            #phone_book_2digits['11'].append('597')
            phone_book_2digits['11'].append('598')
            #phone_book_2digits['11'].append('599')

            phone_book_2digits['11'].append('600')
            # phone_book_2digits['11'].append('601')
            # phone_book_2digits['11'].append('602')
            # phone_book_2digits['11'].append('603')
            # phone_book_2digits['11'].append('604')
            # phone_book_2digits['11'].append('605')
            # phone_book_2digits['11'].append('606')
            # phone_book_2digits['11'].append('607')
            # phone_book_2digits['11'].append('608')
            # phone_book_2digits['11'].append('609')

            #phone_book_2digits['11'].append('610')
            phone_book_2digits['11'].append('611')
            phone_book_2digits['11'].append('612')
            phone_book_2digits['11'].append('613')
            phone_book_2digits['11'].append('614')
            phone_book_2digits['11'].append('615')
            phone_book_2digits['11'].append('616')
            #phone_book_2digits['11'].append('617')
            phone_book_2digits['11'].append('618')
            #phone_book_2digits['11'].append('619')

            #phone_book_2digits['11'].append('620')
            phone_book_2digits['11'].append('621')
            phone_book_2digits['11'].append('622')
            phone_book_2digits['11'].append('623')
            phone_book_2digits['11'].append('624')
            # phone_book_2digits['11'].append('625')
            # phone_book_2digits['11'].append('626')
            # phone_book_2digits['11'].append('627')
            # phone_book_2digits['11'].append('628')
            # phone_book_2digits['11'].append('629')

            #phone_book_2digits['11'].append('630')
            phone_book_2digits['11'].append('631')
            phone_book_2digits['11'].append('632')
            phone_book_2digits['11'].append('633')
            # phone_book_2digits['11'].append('634')
            # phone_book_2digits['11'].append('635')
            # phone_book_2digits['11'].append('636')
            # phone_book_2digits['11'].append('637')
            # phone_book_2digits['11'].append('638')
            # phone_book_2digits['11'].append('639')

            phone_book_2digits['11'].append('640')
            phone_book_2digits['11'].append('641')
            phone_book_2digits['11'].append('642')
            phone_book_2digits['11'].append('643')
            phone_book_2digits['11'].append('644')
            # phone_book_2digits['11'].append('645')
            # phone_book_2digits['11'].append('646')
            # phone_book_2digits['11'].append('647')
            # phone_book_2digits['11'].append('648')
            # phone_book_2digits['11'].append('649')

            # phone_book_2digits['11'].append('650')
            # phone_book_2digits['11'].append('651')
            # phone_book_2digits['11'].append('652')
            # phone_book_2digits['11'].append('653')
            # phone_book_2digits['11'].append('654')
            # phone_book_2digits['11'].append('655')
            # phone_book_2digits['11'].append('656')
            # phone_book_2digits['11'].append('657')
            # phone_book_2digits['11'].append('658')
            # phone_book_2digits['11'].append('659')

            #phone_book_2digits['11'].append('660')
            phone_book_2digits['11'].append('661')
            phone_book_2digits['11'].append('662')
            phone_book_2digits['11'].append('663')
            phone_book_2digits['11'].append('664')
            phone_book_2digits['11'].append('665')
            phone_book_2digits['11'].append('666')
            phone_book_2digits['11'].append('667')
            phone_book_2digits['11'].append('668')
            phone_book_2digits['11'].append('669')

            #phone_book_2digits['11'].append('670')
            phone_book_2digits['11'].append('671')
            # phone_book_2digits['11'].append('672')
            # phone_book_2digits['11'].append('673')
            # phone_book_2digits['11'].append('674')
            # phone_book_2digits['11'].append('675')
            phone_book_2digits['11'].append('676')
            # phone_book_2digits['11'].append('677')
            # phone_book_2digits['11'].append('678')
            # phone_book_2digits['11'].append('679')

            #phone_book_2digits['11'].append('680')
            phone_book_2digits['11'].append('681')
            phone_book_2digits['11'].append('682')
            phone_book_2digits['11'].append('683')
            phone_book_2digits['11'].append('684')
            phone_book_2digits['11'].append('685')
            phone_book_2digits['11'].append('686')
            #phone_book_2digits['11'].append('687')
            phone_book_2digits['11'].append('688')
            #phone_book_2digits['11'].append('689')

            #phone_book_2digits['11'].append('690')
            phone_book_2digits['11'].append('691')
            # phone_book_2digits['11'].append('692')
            # phone_book_2digits['11'].append('693')
            phone_book_2digits['11'].append('694')
            phone_book_2digits['11'].append('695')
            # phone_book_2digits['11'].append('696')
            # phone_book_2digits['11'].append('697')
            # phone_book_2digits['11'].append('698')
            phone_book_2digits['11'].append('699')

            phone_book_2digits['11'].append('700')
            #phone_book_2digits['11'].append('701')
            phone_book_2digits['11'].append('702')
            #phone_book_2digits['11'].append('703')
            phone_book_2digits['11'].append('704')
            #phone_book_2digits['11'].append('705')
            phone_book_2digits['11'].append('706')
            phone_book_2digits['11'].append('707')
            phone_book_2digits['11'].append('708')
            phone_book_2digits['11'].append('709')

            #phone_book_2digits['11'].append('710')
            phone_book_2digits['11'].append('711')
            phone_book_2digits['11'].append('712')
            # phone_book_2digits['11'].append('713')
            # phone_book_2digits['11'].append('714')
            # phone_book_2digits['11'].append('715')
            phone_book_2digits['11'].append('716')
            phone_book_2digits['11'].append('717')
            # phone_book_2digits['11'].append('718')
            # phone_book_2digits['11'].append('719')

            #phone_book_2digits['11'].append('720')
            phone_book_2digits['11'].append('721')
            phone_book_2digits['11'].append('722')
            phone_book_2digits['11'].append('723')
            # phone_book_2digits['11'].append('724')
            # phone_book_2digits['11'].append('725')
            phone_book_2digits['11'].append('726')
            phone_book_2digits['11'].append('727')
            phone_book_2digits['11'].append('728')
            phone_book_2digits['11'].append('729')

            #phone_book_2digits['11'].append('730')
            phone_book_2digits['11'].append('731')
            #phone_book_2digits['11'].append('732')
            phone_book_2digits['11'].append('733')
            # phone_book_2digits['11'].append('734')
            # phone_book_2digits['11'].append('735')
            phone_book_2digits['11'].append('736')
            phone_book_2digits['11'].append('737')
            phone_book_2digits['11'].append('738')
            #phone_book_2digits['11'].append('739')

            #phone_book_2digits['11'].append('740')
            phone_book_2digits['11'].append('741')
            phone_book_2digits['11'].append('742')
            phone_book_2digits['11'].append('743')
            # phone_book_2digits['11'].append('744')
            # phone_book_2digits['11'].append('745')
            phone_book_2digits['11'].append('746')
            phone_book_2digits['11'].append('747')
            phone_book_2digits['11'].append('748')
            #phone_book_2digits['11'].append('749')

            phone_book_2digits['11'].append('750')
            phone_book_2digits['11'].append('751')
            phone_book_2digits['11'].append('752')
            phone_book_2digits['11'].append('753')
            # phone_book_2digits['11'].append('754')
            # phone_book_2digits['11'].append('755')
            phone_book_2digits['11'].append('756')
            phone_book_2digits['11'].append('757')
            phone_book_2digits['11'].append('758')
            #phone_book_2digits['11'].append('759')

            #phone_book_2digits['11'].append('760')
            phone_book_2digits['11'].append('761')
            phone_book_2digits['11'].append('762')
            phone_book_2digits['11'].append('763')
            phone_book_2digits['11'].append('764')
            phone_book_2digits['11'].append('765')
            phone_book_2digits['11'].append('766')
            #phone_book_2digits['11'].append('767')
            phone_book_2digits['11'].append('768')
            phone_book_2digits['11'].append('769')

            phone_book_2digits['11'].append('770')
            phone_book_2digits['11'].append('771')
            phone_book_2digits['11'].append('772')
            phone_book_2digits['11'].append('773')
            phone_book_2digits['11'].append('774')
            phone_book_2digits['11'].append('775')
            phone_book_2digits['11'].append('776')
            phone_book_2digits['11'].append('777')
            phone_book_2digits['11'].append('778')
            #phone_book_2digits['11'].append('779')

            phone_book_2digits['11'].append('780')
            phone_book_2digits['11'].append('781')
            phone_book_2digits['11'].append('782')
            phone_book_2digits['11'].append('783')
            phone_book_2digits['11'].append('784')
            phone_book_2digits['11'].append('785')
            phone_book_2digits['11'].append('786')
            phone_book_2digits['11'].append('787')
            phone_book_2digits['11'].append('788')
            phone_book_2digits['11'].append('789')

            phone_book_2digits['11'].append('790')
            phone_book_2digits['11'].append('791')
            phone_book_2digits['11'].append('792')
            # phone_book_2digits['11'].append('793')
            # phone_book_2digits['11'].append('794')
            phone_book_2digits['11'].append('795')
            phone_book_2digits['11'].append('796')
            phone_book_2digits['11'].append('797')
            phone_book_2digits['11'].append('798')
            phone_book_2digits['11'].append('799')

            #phone_book_2digits['11'].append('800')
            phone_book_2digits['11'].append('801')
            phone_book_2digits['11'].append('802')
            phone_book_2digits['11'].append('803')
            phone_book_2digits['11'].append('804')
            phone_book_2digits['11'].append('805')
            phone_book_2digits['11'].append('806')
            phone_book_2digits['11'].append('807')
            phone_book_2digits['11'].append('808')
            phone_book_2digits['11'].append('809')

            #phone_book_2digits['11'].append('810')
            phone_book_2digits['11'].append('811')
            phone_book_2digits['11'].append('812')
            phone_book_2digits['11'].append('813')
            phone_book_2digits['11'].append('814')
            phone_book_2digits['11'].append('815')
            phone_book_2digits['11'].append('816')
            phone_book_2digits['11'].append('817')
            phone_book_2digits['11'].append('818')
            #phone_book_2digits['11'].append('819')

            phone_book_2digits['11'].append('820')
            phone_book_2digits['11'].append('821')
            phone_book_2digits['11'].append('822')
            phone_book_2digits['11'].append('823')
            phone_book_2digits['11'].append('824')
            phone_book_2digits['11'].append('825')
            phone_book_2digits['11'].append('826')
            phone_book_2digits['11'].append('827')
            phone_book_2digits['11'].append('828')
            #phone_book_2digits['11'].append('829')

            #phone_book_2digits['11'].append('830')
            phone_book_2digits['11'].append('831')
            phone_book_2digits['11'].append('832')
            phone_book_2digits['11'].append('833')
            phone_book_2digits['11'].append('834')
            phone_book_2digits['11'].append('835')
            phone_book_2digits['11'].append('836')
            phone_book_2digits['11'].append('837')
            phone_book_2digits['11'].append('838')
            phone_book_2digits['11'].append('839')

            #phone_book_2digits['11'].append('840')
            phone_book_2digits['11'].append('841')
            phone_book_2digits['11'].append('842')
            # phone_book_2digits['11'].append('843')
            # phone_book_2digits['11'].append('844')
            # phone_book_2digits['11'].append('845')
            phone_book_2digits['11'].append('846')
            # phone_book_2digits['11'].append('847')
            # phone_book_2digits['11'].append('848')
            # phone_book_2digits['11'].append('849')

            phone_book_2digits['11'].append('850')
            phone_book_2digits['11'].append('851')
            phone_book_2digits['11'].append('852')
            phone_book_2digits['11'].append('853')
            phone_book_2digits['11'].append('854')
            phone_book_2digits['11'].append('855')
            phone_book_2digits['11'].append('856')
            phone_book_2digits['11'].append('857')
            phone_book_2digits['11'].append('858')
            phone_book_2digits['11'].append('859')

            phone_book_2digits['11'].append('860')
            phone_book_2digits['11'].append('861')
            phone_book_2digits['11'].append('862')
            phone_book_2digits['11'].append('863')
            phone_book_2digits['11'].append('864')
            phone_book_2digits['11'].append('865')
            phone_book_2digits['11'].append('866')
            phone_book_2digits['11'].append('867')
            phone_book_2digits['11'].append('868')
            #phone_book_2digits['11'].append('869')

            #phone_book_2digits['11'].append('870')
            phone_book_2digits['11'].append('871')
            phone_book_2digits['11'].append('872')
            phone_book_2digits['11'].append('873')
            phone_book_2digits['11'].append('874')
            phone_book_2digits['11'].append('875')
            phone_book_2digits['11'].append('876')
            # phone_book_2digits['11'].append('877')
            # phone_book_2digits['11'].append('878')
            phone_book_2digits['11'].append('879')

            #phone_book_2digits['11'].append('880')
            phone_book_2digits['11'].append('881')
            phone_book_2digits['11'].append('882')
            phone_book_2digits['11'].append('883')
            phone_book_2digits['11'].append('884')
            phone_book_2digits['11'].append('885')
            phone_book_2digits['11'].append('886')
            phone_book_2digits['11'].append('887')
            phone_book_2digits['11'].append('888')
            phone_book_2digits['11'].append('889')

            phone_book_2digits['11'].append('890')
            phone_book_2digits['11'].append('891')
            phone_book_2digits['11'].append('892')
            phone_book_2digits['11'].append('893')
            phone_book_2digits['11'].append('894')
            phone_book_2digits['11'].append('895')
            phone_book_2digits['11'].append('896')
            phone_book_2digits['11'].append('897')
            phone_book_2digits['11'].append('898')
            phone_book_2digits['11'].append('899')

            head_2digits = self._phone_number[1:3]

            if (head_2digits in phone_book_2digits):

                if (self._phone_number[3:6] in phone_book_2digits[head_2digits]):
                    return f"{self._phone_number[0:3]}-{self._phone_number[3:6]}-{self._phone_number[6:]}"

            phone_book_2digits.clear()

            raise ValueError(self._emcreator.message('PhoneNumberBuilder.py','hyphenated','invalid argument',f'the argument ({self._phone_number}) is an incompatible phone number.'))

        raise ValueError(self._emcreator.message('PhoneNumberBuilder.py','hyphenated','invalid argument','the argument must be a 10-digit number.'))
